apiVersion : apps/v1
kind: Deployment
metadata:
  name: shivakantdixitcartservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shivakantdixitcartservice
  template:
    metadata:
      labels:
        app: shivakantdixitcartservice 
    spec:
      containers:
        - name: shivakantdixitcartservice 
          image: cr070920.azurecr.io/shivakantdixitcartservice
          ports:
          - containerPort: 80
